param(
    [Parameter(Mandatory = $true)][string]$GamePath,
    [ValidateSet('zh-cn', 'en')][string]$Language = 'zh-cn',
    [switch]$Test,
    [switch]$BuildShaders,
    [string]$UnityPath = 'C:\Program Files\Unity\Hub\Editor\2022.3.43f1\Editor\Unity.exe'
)
$ErrorActionPreference = 'Stop'
$projectRoot = $PSScriptRoot
if ($BuildShaders) { & (Join-Path $projectRoot 'Build-Shaders.ps1') -UnityPath $UnityPath -Test:$Test }
$shaderBundle = Join-Path $projectRoot 'Files\trainer-highlights'
$shaderBuild = Join-Path $projectRoot 'Files\trainer-highlights.build.json'
if (!(Test-Path -LiteralPath $shaderBundle) -or !(Test-Path -LiteralPath $shaderBuild)) { throw 'Run Build-Shaders.ps1 first, or pass -BuildShaders.' }
$metadata = Get-Content -LiteralPath $shaderBuild -Raw | ConvertFrom-Json
if ((Get-FileHash -LiteralPath $shaderBundle).Hash -ne $metadata.BundleSHA256) { throw 'Shader bundle hash mismatch; rebuild shaders.' }
foreach ($source in $metadata.Sources.PSObject.Properties) {
    $path = Join-Path $projectRoot ('ShaderProject\Assets\Trainer\' + $source.Name)
    if ((Get-FileHash -LiteralPath $path).Hash -ne $source.Value) { throw 'Shader sources changed; run Build-Shaders.ps1 or pass -BuildShaders.' }
}
$gameRoot = (Resolve-Path -LiteralPath $GamePath).Path
$managed = Join-Path $gameRoot 'EscapeFromTarkov_Data\Managed'
if (!(Test-Path -LiteralPath (Join-Path $managed 'Assembly-CSharp.dll'))) { throw 'Game managed assemblies not found.' }
$vswhere = Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe'
$vsRoot = & $vswhere -latest -products '*' -requires Microsoft.Component.MSBuild -property installationPath
if (!$vsRoot) { throw 'Visual Studio MSBuild not found.' }
$msbuild = Join-Path $vsRoot 'MSBuild\Current\Bin\MSBuild.exe'
$output = Join-Path $projectRoot "artifacts\build-$Language"
& $msbuild (Join-Path $projectRoot 'NLog.EFT.Trainer.csproj') -restore -t:Rebuild -nologo -verbosity:minimal '-p:Configuration=Release' "-p:EFTBasePath=$gameRoot" "-p:TrainerLanguage=$Language" "-p:OutputPath=$output\" '-p:DeployToGame=false'
if ($LASTEXITCODE -ne 0) { throw 'Trainer build failed.' }
$package = Join-Path $projectRoot "artifacts\visible-esp-$Language"
$null = New-Item -ItemType Directory -Path $package -Force
Copy-Item -LiteralPath (Join-Path $output 'NLog.EFT.Trainer.dll') -Destination $package
Copy-Item -LiteralPath $shaderBundle,$shaderBuild -Destination $package
Copy-Item -LiteralPath (Join-Path $projectRoot 'docs\VISIBLE-ESP.md') -Destination $package
Copy-Item -LiteralPath (Join-Path $projectRoot 'Install-Local.ps1') -Destination $package
if ($Test) {
    $testOutput = Join-Path $projectRoot 'artifacts\tests'
    $null = New-Item -ItemType Directory -Path $testOutput -Force
    $core = Join-Path $managed 'UnityEngine.CoreModule.dll'
    $compiler = Join-Path $vsRoot 'MSBuild\Current\Bin\Roslyn\csc.exe'
    $netstandard = Join-Path $managed 'netstandard.dll'
    & $compiler -nologo -langversion:latest "-r:$core" "-r:$netstandard" "-out:$testOutput\EspGeometryTests.exe" (Join-Path $projectRoot 'Features\EspGeometry.cs') (Join-Path $projectRoot 'Tests\EspGeometryTests.cs')
    if ($LASTEXITCODE -ne 0) { throw 'Geometry test compilation failed.' }
    Copy-Item -LiteralPath $core -Destination $testOutput -Force
    Copy-Item -LiteralPath $netstandard -Destination $testOutput -Force
    & (Join-Path $testOutput 'EspGeometryTests.exe')
    if ($LASTEXITCODE -ne 0) { throw 'Geometry regression tests failed.' }
    # EFT's modified JSON assembly fails desktop CLR strong-name verification.
    # Use MSBuild's signed copy of the same assembly version only for the standalone tests.
    $json = Join-Path $vsRoot 'MSBuild\Current\Bin\Newtonsoft.Json.dll'
    $gameJson = Join-Path $managed 'Newtonsoft.Json.dll'
    if ([Reflection.AssemblyName]::GetAssemblyName($json).FullName -ne [Reflection.AssemblyName]::GetAssemblyName($gameJson).FullName) {
        throw 'Settings tests require a signed Newtonsoft.Json matching the game assembly version.'
    }
    # Use the resource generated by the trainer build so status text is tested in the packaged language.
    $settingsResource = Join-Path $projectRoot 'obj\Release\EFT.Trainer.Properties.Strings.resources'
    if ($Language -eq 'zh-cn') { $settingsResource = Join-Path $projectRoot 'obj\Release\EFT.Trainer.Properties.Strings.zh-cn.resources' }
    $settingsSources = @(
        'Configuration\ConfigurationManager.cs', 'Configuration\ConfigurationPropertyAttribute.cs',
        'Configuration\OrderedProperty.cs', 'Configuration\ColorConverter.cs',
        'Configuration\KeyCodeConverter.cs', 'Configuration\TrackedItemConverter.cs',
        'Features\PlayerColor.cs', 'Features\TrackedItem.cs', 'Extensions\PlayerTeam.cs',
        'Properties\Strings.Designer.cs', 'Tests\SettingsTestStubs.cs', 'Tests\SettingsTests.cs'
    ) | ForEach-Object { Join-Path $projectRoot $_ }
    & $compiler -nologo -langversion:latest "-r:$core" "-r:$netstandard" "-r:$json" "-resource:$settingsResource,EFT.Trainer.Properties.Strings.resources" "-out:$testOutput\SettingsTests.exe" $settingsSources
    if ($LASTEXITCODE -ne 0) { throw 'Settings test compilation failed.' }
    Copy-Item -LiteralPath $json -Destination $testOutput -Force
    Copy-Item -LiteralPath (Join-Path $managed 'UnityEngine.SharedInternalsModule.dll') -Destination $testOutput -Force
    & (Join-Path $testOutput 'SettingsTests.exe') (Join-Path $testOutput 'settings-fixtures')
    if ($LASTEXITCODE -ne 0) { throw 'Settings and team regression tests failed.' }
}
Write-Host "Package: $package"
